apiVersion: apps/v1
kind: Deployment
metadata:
  name: pwar-deployment
spec:
  selector:
    matchLabels:
      app: pwar
  replicas: 2 # tells deployment to run 2 pods matching the template
  template:
    metadata:
      labels:
        app: pwar
    spec:
      containers:
      - name: pwar
        image: aldodockerhub/pipeline:latest
        ports:
        - containerPort: 8080
