apiVersion: v1
kind: Service
metadata:
  name: pwar-service
spec:
  type: NodePort      
  selector:
    app: pwar

  ports:
  - name: http
    targetPort: 8080
    port: 8080
    nodePort: 30080
    protocol: TCP
